object Module {
    const val kotlinUtil = ":utility:kotlin-util"
    const val androidUtil = ":utility:android-util"
    const val uiComponent = ":ui-component"
    const val domain = ":domain"
    const val about = ":feature:about"
    const val settings = ":feature:settings"
    const val alarmPublic = ":feature:alarm:public"
    const val alarmImpl = ":feature:alarm:impl"
    const val taskHistory = ":feature:task-history"
    const val taskForm = ":feature:task-form"
    const val taskListPublic = ":feature:task-list:public"
    const val taskListImpl = ":feature:task-list:impl"
    const val taskDetailsPublic = ":feature:task-details:public"
    const val taskDetailsImpl = ":feature:task-details:impl"
}