object Module {
    const val kotlinUtil = ":utility:kotlin-util"
    const val androidUtil = ":utility:android-util"
    const val uiComponent = ":ui-component"
    const val domain = ":domain"
    const val aboutPublic = ":feature:about:public"
    const val aboutImpl = ":feature:about:impl"
    const val settings = ":feature:settings"
    const val settingsPublic = ":feature:settings:public"
    const val settingsImpl = ":feature:settings:impl"
    const val alarmPublic = ":feature:alarm:public"
    const val alarmImpl = ":feature:alarm:impl"
    const val taskHistoryPublic = ":feature:task-history:public"
    const val taskHistoryImpl = ":feature:task-history:impl"
    const val taskFormPublic = ":feature:task-form:public"
    const val taskFormImpl = ":feature:task-form:impl"
    const val taskListPublic = ":feature:task-list:public"
    const val taskListImpl = ":feature:task-list:impl"
    const val taskDetailsPublic = ":feature:task-details:public"
    const val taskDetailsImpl = ":feature:task-details:impl"
}